### ISSUE TITLE
Unexpected end-group tag

### ISSUE THREAD

**Issue by kmatt** [spotify/snakebite#190]
Python 2.7 on OS X 10.10, protobuf (2.6.1), snakebite (2.7.2):

```
File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.
```

**Comment by kmatt** [comment]
Full debug output:

```
$ /Users/mattk/Library/Python/2.7/bin/snakebite -D ls testpath
DEBUG:snakebite.client:Switch to namenode: es05:50070
DEBUG:snakebite.client:Created client for es05:50070 with trash=False and sasl=False
DEBUG:snakebite.client:Trying to find path /user/mattk/testpath
DEBUG:snakebite.channel:############## CONNECTING ##############
DEBUG:snakebite.channel:Sending: 68 72 70 63 (len: 4)
DEBUG:snakebite.channel:Sending: 09 (len: 1)
DEBUG:snakebite.channel:Sending: 00 (len: 1)
DEBUG:snakebite.channel:Sending: 00 (len: 1)
DEBUG:snakebite.channel:RpcRequestHeaderProto (len: 26):

rpcKind: RPC_PROTOCOL_BUFFER
rpcOp: RPC_FINAL_PACKET
callId: -3
clientId: "cea5ba79-e7ca-48"
retryCount: -1

DEBUG:snakebite.channel:RequestContext (len: 60):

userInfo {
  effectiveUser: "mattk"
}
protocol: "org.apache.hadoop.hdfs.protocol.ClientProtocol"

DEBUG:snakebite.channel:Header length: 88 (00 00 00 58 (len: 4))
DEBUG:snakebite.channel:Sending: 00 00 00 58 (len: 4)
DEBUG:snakebite.channel:Sending: 1a (len: 1)
DEBUG:snakebite.channel:Sending: 08 02 10 00 18 05 22 10 63 65 61 35 62 61 37 39 2d 65 37 63 61 2d 34 38 28 01 (len: 26)
DEBUG:snakebite.channel:Sending: 3c (len: 1)
DEBUG:snakebite.channel:Sending: 12 0a 0a 08 6d 6b 65 72 61 6e 65 6e 1a 2e 6f 72 67 2e 61 70 61 63 68 65 2e 68 61 64 6f 6f 70 2e 68 64 66 73 2e 70 72 6f 74 6f 63 6f 6c 2e 43 6c 69 65 6e 74 50 72 6f 74 6f 63 6f 6c (len: 60)
DEBUG:snakebite.channel:############## SENDING ##############
DEBUG:snakebite.channel:RpcRequestHeaderProto (len: 26):

rpcKind: RPC_PROTOCOL_BUFFER
rpcOp: RPC_FINAL_PACKET
callId: 0
clientId: "cea5ba79-e7ca-48"
retryCount: -1

DEBUG:snakebite.channel:RequestHeaderProto (len: 63):

methodName: "getFileInfo"
declaringClassProtocolName: "org.apache.hadoop.hdfs.protocol.ClientProtocol"
clientProtocolVersion: 1

DEBUG:snakebite.channel:Request:

src: "/user/mattk/testpath"

DEBUG:snakebite.channel:RPC message length: 114 (00 00 00 72 (len: 4))
DEBUG:snakebite.channel:Sending: 00 00 00 72 (len: 4)
DEBUG:snakebite.channel:Sending: 1a (len: 1)
DEBUG:snakebite.channel:Sending: 08 02 10 00 18 00 22 10 63 65 61 35 62 61 37 39 2d 65 37 63 61 2d 34 38 28 01 (len: 26)
DEBUG:snakebite.channel:Sending: 3f (len: 1)
DEBUG:snakebite.channel:Sending: 0a 0b 67 65 74 46 69 6c 65 49 6e 66 6f 12 2e 6f 72 67 2e 61 70 61 63 68 65 2e 68 61 64 6f 6f 70 2e 68 64 66 73 2e 70 72 6f 74 6f 63 6f 6c 2e 43 6c 69 65 6e 74 50 72 6f 74 6f 63 6f 6c 18 01 (len: 63)
DEBUG:snakebite.channel:Sending: 16 (len: 1)
DEBUG:snakebite.channel:Sending: 0a 14 2f 75 73 65 72 2f 6d 6b 65 72 61 6e 65 6e 2f 63 61 73 70 72 (len: 22)
DEBUG:snakebite.channel:############## RECVING ##############
DEBUG:snakebite.channel:############## PARSING ##############
DEBUG:snakebite.channel:Payload class: <class 'snakebite.protobuf.ClientNamenodeProtocol_pb2.GetFileInfoResponseProto'>
DEBUG:snakebite.channel:Bytes read: 4, total: 4
DEBUG:snakebite.channel:Total response length: 1213486160
DEBUG:snakebite.channel:Bytes read: 4, total: 8
DEBUG:snakebite.channel:Delimited message length (pos 1): 47
DEBUG:snakebite.channel:Rewinding pos 7 with 3 places
DEBUG:snakebite.channel:Reset buffer to pos 4
DEBUG:snakebite.channel:Bytes read: 44, total: 52
DEBUG:snakebite.channel:Delimited message bytes (47): 31 2e 31 20 34 30 30 20 42 61 64 20 52 65 71 75 65 73 74 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 53 65 72 76 65 72 3a (len: 47)
DEBUG:snakebite.channel:Header read 48
DEBUG:snakebite.channel:Closing socket
Traceback (most recent call last):
  File "/Users/mattk/Library/Python/2.7/bin/snakebite", line 38, in <module>
    SnakebiteCli()
  File "/Users/mattk/Library/Python/2.7/bin/snakebite", line 29, in __init__
    clparser.execute()
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/commandlineparser.py", line 460, in execute
    exitError(sys.exc_info())
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/commandlineparser.py", line 455, in execute
    return Commands.methods[self.cmd]['method'](self)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/commandlineparser.py", line 490, in ls
    for line in self._listing():
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/commandlineparser.py", line 511, in _listing
    summary=self.args.summary):
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/formatter.py", line 93, in format_listing
    node = listing.next()
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/client.py", line 1445, in wrapped
    yield results.next()
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/client.py", line 152, in ls
    recurse=recurse):
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/client.py", line 1198, in _find_items
    fileinfo = self._get_file_info(path)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/client.py", line 1326, in _get_file_info
    return self.service.getFileInfo(request)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/service.py", line 35, in <lambda>
    rpc = lambda request, service=self, method=method.name: service.call(service_stub_class.__dict__[method], request)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/service.py", line 41, in call
    return method(self.service, controller, request)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/google/protobuf/service_reflection.py", line 267, in <lambda>
    self._StubMethod(inst, method, rpc_controller, request, callback))
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/google/protobuf/service_reflection.py", line 284, in _StubMethod
    method_descriptor.output_type._concrete_class, callback)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/channel.py", line 440, in CallMethod
    return self.parse_response(byte_stream, response_class)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/snakebite/channel.py", line 396, in parse_response
    header.ParseFromString(header_bytes)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/google/protobuf/message.py", line 186, in ParseFromString
    self.MergeFromString(serialized)
  File "/Users/mattk/Library/Python/2.7/lib/python/site-packages/google/protobuf/internal/python_message.py", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
google.protobuf.message.DecodeError: Unexpected end-group tag.
```

**Comment by wouterdebie** [comment]
What hadoop version are you running?

**Comment by kmatt** [comment]
Missed this in email. Was running Hadoop 2.7.0 at the time.
